---

- name: Display Cisco IOS versions
  hosts: router_type2
  gather_facts: true

  tasks:
    - name: run show version on target devices
      ios_command:
        commands: show version | incl IOS XE Software
      register: output

    - name: print output
      debug:
        var: output.stdout_lines
