- hosts: f38c1
  become: true
  gather_facts: false

  vars:
    file_path: "./top5.txt"
    file_contents: |
      London
      Paris
      New York
      Sydney
      Tokyo

  tasks:
    - name: check if file exists
      stat:
        path: "{{ file_path }}"
      register: file_info

    - name: create file if it does not exist
      file:
        path: "{{ file_path }}"
        state: touch
        mode: "0666"
      when: not file_info.stat.exists

    - name: ensure file has specific contents
      copy:
        dest: "{{ file_path }}"
        content: "{{ file_contents }}"
      notify: file_changed

  handlers:
    - name: file_changed
      command: echo "Your file has been changed!"
