---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Read file content
    command: cat /etc/passwd
    register: file_output
    become: true

  - name: View the last three lines of the file
    debug: # print the contents of the file_output variable
      msg: "{{ file_output.stdout_lines[-3:] }}" 
