---

- hosts: all
  become: true
  tasks:
    - name: update package cache
      ansible.builtin.package:
        update_cache: yes
      changed_when: false
      tags: [always, update]

- hosts: all
  become: true
  roles:
    - base
    - db_servers
    - file_servers
    - web_servers
