- name: Update package cache on Fedora 38 servers
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      dnf:
        update_cache: yes
      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version == '38'
