---
- hosts: all
  become: true

  tasks:
    - name: Update package cache on Red Hat distros
      dnf:
        update_cache: yes
      when: ansible_distribution in ['Fedora', 'Red Hat', 'CentOS']

    - name: Update package cache on Debian distros
      apt:
        update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian',  'Pop!_OS']

    - name: Install apache2 package on Ubuntu
      apt:
        name: apache2
      when: ansible_distribution == "Ubuntu"

    - name: Install httpd package on Fedora
      dnf:
        name: httpd # The package name is different
      when: ansible_distribution == "Fedora"
