---
- hosts: all
  become: true

  tasks:
    - name: Update package cache on Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution=='Ubuntu'

    - name: Install packages on Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - tmux
          - tree
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache on Fedora
      dnf:
        update_cache: yes
      when: ansible_distribution=='Fedora'

    - name: Install packages on Fedora
      dnf:
        name:
          - httpd
          - php
          - tmux
          - tree
        state: latest
      when: ansible_distribution == "Fedora"
