---
- name: Test playbook for ignore_errors
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Failing task
      ansible.builtin.command: /bin/DodgyApp
#      ignore_errors: yes

    - name: Non-failing task
      ansible.builtin.debug:
        msg: "Work hard, play hard and always keep at school!"
