---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes

  - name: Install apache2 package
    ansible.builtin.apt:
      name:  apache2
