---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install apache2 package
    apt:
      name:  apache2
  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
