---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Set my_variable fact
      set_fact:
        my_variable: 'Barbie'
    - name: Print Hi, Tom!
      debug:
        msg: "Hi, {{ my_variable | default('Tom') }}!"
